CREATE VIEW V_ISTA AS

SELECT A.NAME AS STUDENT_NAME, A.COURSE_ID, B.NAME AS INSTRUCTORE_NAME
FROM (SELECT S.NAME, T.COURSE_ID
FROM STUDENT S JOIN TAKES T
    ON S.ID = T.ID) A
JOIN     
(SELECT I.NAME, C.COURSE_ID
FROM TEACHES C LEFT JOIN INSTRUCTOR I
    ON C.ID = I.ID) B
    ON A.COURSE_ID = B.COURSE_ID
GROUP BY A.NAME, A.COURSE_ID, B.NAME; 

GRANT SELECT ON V_ISTA TO IS101008;

SELECT * 
FROM V_ISTA 
WHERE INSTRUCTORE_NAME = NULL;

SELECT *
FROM IS101008.VISTA_1
WHERE INSTRUCTOR_NAME = NULL;

SELECT *
FROM IS101008.VISTA_1;

SELECT * 
FROM COURSE;

SELECT *
FROM PREREQ;

SELECT  C.TITLE NOMBRE_CURSO , CP.TITLE NOMBRE_PREREQUISITO
FROM COURSE C LEFT JOIN PREREQ P 
    ON C.COURSE_ID = P.COURSE_ID
LEFT JOIN COURSE CP 
    ON P.PREREQ_ID = CP.COURSE_ID; 

CREATE VIEW V_PREREQUISITO AS 
SELECT P.PREREQ_ID ID, C.TITLE NOMBRE
FROM COURSE C LEFT JOIN PREREQ P 
    ON C.COURSE_ID = P.COURSE_ID; 
    
GRANT SELECT, INSERT ON V_PREREQUISITO TO IS101008; 

CREATE MATERIALIZED VIEW NUEVO_PREREQUISITO AS
SELECT  C.TITLE NOMBRE_CURSO , CP.TITLE NOMBRE_PREREQUISITO
FROM COURSE C LEFT JOIN PREREQ P 
    ON C.COURSE_ID = P.COURSE_ID
LEFT JOIN COURSE CP 
    ON P.PREREQ_ID = CP.COURSE_ID; 
