-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-10-04 17:28:44 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACREDITACION_PRENSA 
    ( 
     id_acreditacion   INTEGER  NOT NULL , 
     id_persona        INTEGER  NOT NULL , 
     id_edicion        INTEGER  NOT NULL , 
     medio_comunicacio VARCHAR2 (120 CHAR)  NOT NULL , 
     fecha_emision     DATE  NOT NULL , 
     tipo_acreditacion VARCHAR2 (40 CHAR)  NOT NULL , 
     estado            VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE ACREDITACION_PRENSA 
    ADD CONSTRAINT ACREDITACION_PRENSA_PK PRIMARY KEY ( id_acreditacion ) ;

CREATE TABLE ASIGNACION_ARBITRAL 
    ( 
     id_asignacion INTEGER  NOT NULL , 
     id_partido    INTEGER  NOT NULL , 
     id_persona    INTEGER  NOT NULL , 
     rol_arbitral  VARCHAR2 (40 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE ASIGNACION_ARBITRAL 
    ADD CONSTRAINT ASIGNACION_ARBITRAL_PK PRIMARY KEY ( id_asignacion ) ;

ALTER TABLE ASIGNACION_ARBITRAL 
    ADD CONSTRAINT Unique_Key_1 UNIQUE ( rol_arbitral , id_partido ) ;

ALTER TABLE ASIGNACION_ARBITRAL 
    ADD CONSTRAINT Unique_Key_2 UNIQUE ( id_partido , id_persona ) ;

CREATE TABLE AUDITORIA 
    ( 
     id_auditoria         INTEGER  NOT NULL , 
     usuario_bd           VARCHAR2 (100 CHAR)  NOT NULL , 
     tabla_afectada       VARCHAR2 (50 CHAR)  NOT NULL , 
     id_registro_afectado INTEGER  NOT NULL , 
     operacion            VARCHAR2 (10 CHAR)  NOT NULL , 
     fecha_hora           TIMESTAMP  NOT NULL , 
     valor_anterior       CLOB , 
     valor_nuevo          CLOB 
    ) 
;

ALTER TABLE AUDITORIA 
    ADD CONSTRAINT AUDITORIA_PK PRIMARY KEY ( id_auditoria ) ;

CREATE TABLE CIUDAD 
    ( 
     id_ciudad INTEGER  NOT NULL , 
     id_sede   INTEGER  NOT NULL , 
     nombre    VARCHAR2 (80 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( id_ciudad ) ;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT Unique_Key UNIQUE ( id_sede , nombre ) ;

CREATE TABLE EDICION_MUNDIAL 
    ( 
     id_edicion   INTEGER  NOT NULL , 
     anio         NUMBER  NOT NULL , 
     nombre       VARCHAR2 (100 CHAR)  NOT NULL , 
     fecha_inicio DATE  NOT NULL , 
     fecha_fin    DATE  NOT NULL 
    ) 
;

ALTER TABLE EDICION_MUNDIAL 
    ADD CONSTRAINT EDICION_MUNDIAL_PK PRIMARY KEY ( id_edicion ) ;

ALTER TABLE EDICION_MUNDIAL 
    ADD CONSTRAINT anio UNIQUE ( anio ) ;

CREATE TABLE ENTRADA 
    ( 
     id_entrada INTEGER  NOT NULL , 
     id_partido INTEGER  NOT NULL , 
     categoria  VARCHAR2 (30 CHAR)  NOT NULL , 
     zona       VARCHAR2 (50 CHAR)  NOT NULL , 
     precio     NUMBER (2,10)  NOT NULL , 
     estado     VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE ENTRADA 
    ADD CONSTRAINT ENTRADA_PK PRIMARY KEY ( id_entrada ) ;

CREATE TABLE Estadio 
    ( 
     id_estadio INTEGER  NOT NULL , 
     id_ciudad  INTEGER  NOT NULL , 
     nombre     VARCHAR2 (100 CHAR)  NOT NULL , 
     capacidad  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Estadio 
    ADD CONSTRAINT Estadio_PK PRIMARY KEY ( id_estadio ) ;

ALTER TABLE Estadio 
    ADD CONSTRAINT Unique_Keyv4 UNIQUE ( nombre , id_ciudad ) ;

CREATE TABLE ETAPA_COMPETENCIA 
    ( 
     id_etapa       INTEGER  NOT NULL , 
     id_edicion     INTEGER  NOT NULL , 
     id_etapa_padre INTEGER , 
     nombre         VARCHAR2 (80 CHAR)  NOT NULL , 
     tipo_etapa     VARCHAR2 (40)  NOT NULL , 
     orden          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ETAPA_COMPETENCIA 
    ADD CONSTRAINT ETAPA_COMPETENCIA_PK PRIMARY KEY ( id_etapa ) ;

CREATE TABLE EVENTO_PARTIDO 
    ( 
     id_evento              INTEGER  NOT NULL , 
     id_partido             INTEGER  NOT NULL , 
     id_persona             INTEGER , 
     id_persona_relacionada INTEGER , 
     tipo_evento            VARCHAR2 (40 CHAR)  NOT NULL , 
     minuto                 SMALLINT , 
     valor_numerico         SMALLINT , 
     descripcion            VARCHAR2 (400 CHAR) 
    ) 
;

ALTER TABLE EVENTO_PARTIDO 
    ADD CONSTRAINT EVENTO_PARTIDO_PK PRIMARY KEY ( id_evento ) ;

CREATE TABLE ORGANIZACIONES_FUTBOL 
    ( 
     id_organizacion       INTEGER  NOT NULL , 
     nombre                VARCHAR2 (100 CHAR)  NOT NULL , 
     tipo                  VARCHAR2 (30 CHAR)  NOT NULL , 
     pais                  VARCHAR2 (80 CHAR)  NOT NULL , 
     id_organizacion_padre INTEGER 
    ) 
;

ALTER TABLE ORGANIZACIONES_FUTBOL 
    ADD CONSTRAINT ORGANIZACIONES_FUTBOL_PK PRIMARY KEY ( id_organizacion ) ;

CREATE TABLE PARTICIPACION_PARTIDO 
    ( 
     id_participacion_partido INTEGER  NOT NULL , 
     id_partido               INTEGER  NOT NULL , 
     id_seleccion             INTEGER  NOT NULL , 
     condicion                VARCHAR2 (10 CHAR)  NOT NULL , 
     goles                    INTEGER  NOT NULL , 
     goles_penales            INTEGER  NOT NULL , 
     resultado                VARCHAR2 (10) 
    ) 
;

ALTER TABLE PARTICIPACION_PARTIDO 
    ADD CONSTRAINT PARTICIPACION_PARTIDO_PK PRIMARY KEY ( id_participacion_partido ) ;

ALTER TABLE PARTICIPACION_PARTIDO 
    ADD CONSTRAINT Unique_Key_1v2 UNIQUE ( id_seleccion , id_partido ) ;

ALTER TABLE PARTICIPACION_PARTIDO 
    ADD CONSTRAINT Unique_Key_2v2 UNIQUE ( condicion , id_seleccion ) ;

CREATE TABLE PARTIDO 
    ( 
     id_partido            INTEGER  NOT NULL , 
     id_etapa              INTEGER  NOT NULL , 
     id_estadio            INTEGER  NOT NULL , 
     id_partido_origen_1   INTEGER , 
     id_partido_origen_2   INTEGER , 
     fecha_hora            DATE  NOT NULL , 
     asistencia_registrada INTEGER  NOT NULL , 
     estado                VARCHAR2 (30 CHAR)  NOT NULL , 
     resultado_origen_1    VARCHAR2 (20 CHAR) , 
     resultado_origen_2    VARCHAR2 (20 CHAR) 
    ) 
;

ALTER TABLE PARTIDO 
    ADD CONSTRAINT PARTIDO_PK PRIMARY KEY ( id_partido ) ;

CREATE TABLE PERSONA 
    ( 
     id_persona          INTEGER  NOT NULL , 
     nombre_completo     VARCHAR2 (120 CHAR)  NOT NULL , 
     nacionalidad        VARCHAR2 (80 CHAR) , 
     fecha_de_nacimiento DATE 
    ) 
;

ALTER TABLE PERSONA 
    ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( id_persona ) ;

CREATE TABLE SEDE 
    ( 
     id_sede    INTEGER  NOT NULL , 
     id_edicion INTEGER  NOT NULL , 
     pais       VARCHAR2 (80 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SEDE 
    ADD CONSTRAINT SEDE_PK PRIMARY KEY ( id_sede ) ;

ALTER TABLE SEDE 
    ADD CONSTRAINT Unique_Keyv1 UNIQUE ( pais , id_edicion ) ;

CREATE TABLE SELECCION 
    ( 
     id_seleccion    INTEGER  NOT NULL , 
     id_organizacion INTEGER  NOT NULL , 
     id_etapa_grupo  INTEGER  NOT NULL , 
     codigo_fifa     VARCHAR2 (3 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SELECCION 
    ADD CONSTRAINT SELECCION_PK PRIMARY KEY ( id_seleccion ) ;

CREATE TABLE VINCULACION_SELECCION 
    ( 
     id_vinculacion INTEGER  NOT NULL , 
     id_persona     INTEGER  NOT NULL , 
     id_seleccion   INTEGER  NOT NULL , 
     capitan        CHAR (1 CHAR) , 
     dorsal         SMALLINT , 
     posicion       VARCHAR2 (30) , 
     rol            VARCHAR2 (30 CHAR)  NOT NULL , 
     club           VARCHAR2 (120 CHAR) 
    ) 
;

ALTER TABLE VINCULACION_SELECCION 
    ADD CONSTRAINT VINCULACION_SELECCION_PK PRIMARY KEY ( id_vinculacion ) ;

ALTER TABLE VINCULACION_SELECCION 
    ADD CONSTRAINT Unique_Keyv2 UNIQUE ( id_seleccion , id_persona ) ;

ALTER TABLE ACREDITACION_PRENSA 
    ADD CONSTRAINT acredita FOREIGN KEY 
    ( 
     id_edicion
    ) 
    REFERENCES EDICION_MUNDIAL 
    ( 
     id_edicion
    ) 
;

ALTER TABLE SELECCION 
    ADD CONSTRAINT agrupa FOREIGN KEY 
    ( 
     id_etapa_grupo
    ) 
    REFERENCES ETAPA_COMPETENCIA 
    ( 
     id_etapa
    ) 
;

ALTER TABLE PARTIDO 
    ADD CONSTRAINT alberga FOREIGN KEY 
    ( 
     id_estadio
    ) 
    REFERENCES Estadio 
    ( 
     id_estadio
    ) 
;

ALTER TABLE PARTIDO 
    ADD CONSTRAINT contiene FOREIGN KEY 
    ( 
     id_etapa
    ) 
    REFERENCES ETAPA_COMPETENCIA 
    ( 
     id_etapa
    ) 
;

ALTER TABLE VINCULACION_SELECCION 
    ADD CONSTRAINT crea FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE ETAPA_COMPETENCIA 
    ADD CONSTRAINT cuenta_con FOREIGN KEY 
    ( 
     id_edicion
    ) 
    REFERENCES EDICION_MUNDIAL 
    ( 
     id_edicion
    ) 
;

ALTER TABLE Estadio 
    ADD CONSTRAINT dispone FOREIGN KEY 
    ( 
     id_ciudad
    ) 
    REFERENCES CIUDAD 
    ( 
     id_ciudad
    ) 
;

ALTER TABLE ASIGNACION_ARBITRAL 
    ADD CONSTRAINT es FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE EVENTO_PARTIDO 
    ADD CONSTRAINT genera FOREIGN KEY 
    ( 
     id_partido
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
;

ALTER TABLE EVENTO_PARTIDO 
    ADD CONSTRAINT involucra FOREIGN KEY 
    ( 
     id_persona_relacionada
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE PARTIDO 
    ADD CONSTRAINT P2precede FOREIGN KEY 
    ( 
     id_partido_origen_1
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT posee FOREIGN KEY 
    ( 
     id_sede
    ) 
    REFERENCES SEDE 
    ( 
     id_sede
    ) 
;

ALTER TABLE PARTIDO 
    ADD CONSTRAINT precede FOREIGN KEY 
    ( 
     id_partido_origen_2
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
;

ALTER TABLE ACREDITACION_PRENSA 
    ADD CONSTRAINT recibe FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE PARTICIPACION_PARTIDO 
    ADD CONSTRAINT registra FOREIGN KEY 
    ( 
     id_seleccion
    ) 
    REFERENCES SELECCION 
    ( 
     id_seleccion
    ) 
;

ALTER TABLE EVENTO_PARTIDO 
    ADD CONSTRAINT relaciona FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE PARTICIPACION_PARTIDO 
    ADD CONSTRAINT rellena FOREIGN KEY 
    ( 
     id_partido
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE SELECCION 
    ADD CONSTRAINT representa FOREIGN KEY 
    ( 
     id_organizacion
    ) 
    REFERENCES ORGANIZACIONES_FUTBOL 
    ( 
     id_organizacion
    ) 
;

ALTER TABLE ETAPA_COMPETENCIA 
    ADD CONSTRAINT se_conforma FOREIGN KEY 
    ( 
     id_etapa_padre
    ) 
    REFERENCES ETAPA_COMPETENCIA 
    ( 
     id_etapa
    ) 
;

ALTER TABLE ORGANIZACIONES_FUTBOL 
    ADD CONSTRAINT se_forma_de FOREIGN KEY 
    ( 
     id_organizacion_padre
    ) 
    REFERENCES ORGANIZACIONES_FUTBOL 
    ( 
     id_organizacion
    ) 
;

ALTER TABLE SEDE 
    ADD CONSTRAINT tiene FOREIGN KEY 
    ( 
     id_edicion
    ) 
    REFERENCES EDICION_MUNDIAL 
    ( 
     id_edicion
    ) 
;

ALTER TABLE ENTRADA 
    ADD CONSTRAINT tienev1 FOREIGN KEY 
    ( 
     id_partido
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
;

ALTER TABLE ASIGNACION_ARBITRAL 
    ADD CONSTRAINT tienev2 FOREIGN KEY 
    ( 
     id_partido
    ) 
    REFERENCES PARTIDO 
    ( 
     id_partido
    ) 
;

ALTER TABLE VINCULACION_SELECCION 
    ADD CONSTRAINT vincula FOREIGN KEY 
    ( 
     id_seleccion
    ) 
    REFERENCES SELECCION 
    ( 
     id_seleccion
    ) 
;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             49
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
