-- ==================================================
-- Rol Operativo a Jerónimo (GRANT ALL) 
-- ==================================================
GRANT ALL ON EDICION_MUNDIAL TO is101008;
GRANT ALL ON SELECCION TO is101008;
GRANT ALL ON JUGADOR TO is101008;
GRANT ALL ON CONVOCADOS_POR_EDICION TO is101008;
GRANT ALL ON ESTADIO TO is101008;
GRANT ALL ON PARTIDO TO is101008;
GRANT ALL ON PARTICIPACION_PARTIDO TO is101008;

-- ==================================================
-- Rol Seleccion a Camilo (GRANT SELECT) 
-- ==================================================
GRANT SELECT ON EDICION_MUNDIAL TO is101000;
GRANT SELECT ON SELECCION TO is101000;
GRANT SELECT ON JUGADOR TO is101000;
GRANT SELECT ON CONVOCADOS_POR_EDICION TO is101000;
GRANT SELECT ON ESTADIO TO is101000;
GRANT SELECT ON PARTIDO TO is101000;
GRANT SELECT ON PARTICIPACION_PARTIDO TO is101000;